### ISSUE TITLE
Close button not correctly displayed on launch screen

### ISSUE THREAD

**Issue by zeruniverse** [USBA/Human-shell-theme#4]
Hi, I love this theme and have been using this for more than a year, thanks for your work!

Recently after upgrading my system (and Gnome), the close button for windows on lauch screen stops working correctly. Could you fix this? I'm on Gnome 3.32.2 (ArchLinux) and Human 4.9 (newest from opendesktop). 

Images below further explain this problem. (when not on focus, the close button has a weird blue circle around it, while on focus, some weird black stripe shadow shows up)

![ezgif-2-430cbcefd3c0](https://user-images.githubusercontent.com/4648756/60625471-c362c580-9d9c-11e9-9070-0edfaeb41c20.gif)

**Comment by USBA** [comment]
@zeruniverse thanks for reporting this issue and thanks for using my theme 😃 
Check the latest version. I did some changes and I thing I fixed it.

Have a great day.

**Comment by zeruniverse** [comment]
fix confirmed! Thanks!
